@startuml
title Diagrama de Sequência: Registro e Atracação de Carga Comum
hide footbox

actor "Admin do Porto" as Admin
participant "app.py (CLI)" as CLI
participant "controller_cadastros" as CtrlCad
participant "controller_operacao" as CtrlOp
participant "ord_propriety" as MotorFila
database "porto.db (SQLAlchemy)" as DB

Admin -> CLI: Escolhe Registrar Navio Manualmente (Balcão)
activate CLI
CLI -> CtrlCad: solicitar_pre_cadastro(session, imo, nome, capitao, companhia, carga_desc, categoria, peso, eh_perecivel=False, possui_documentos=True)
activate CtrlCad
CtrlCad -> DB: Instancia Navio(status=PENDENTE) e Carga(eh_perecivel=False, documento_alfandega=True)
CtrlCad -> DB: session.add() & session.commit()
CtrlCad --> CLI: Confirmação de Pré-Cadastro
deactivate CtrlCad

Admin -> CLI: Escolhe Auditar Solicitações Pendentes
CLI -> CtrlCad: auditar_solicitacoes_pendentes(session)
activate CtrlCad
CtrlCad -> DB: Busca Navios com status == StatusNavio.PENDENTE
CtrlCad -> CtrlCad: _auditar_documentacao_navio(navio)
note right: Verifica se\ncarga.documento_alfandega == True
CtrlCad -> DB: Atualiza navio.status = StatusNavio.VALIDADO
CtrlCad -> DB: session.commit()
CtrlCad --> CLI: Navio aprovado para a Fila Oficial
deactivate CtrlCad

Admin -> CLI: Escolhe Iniciar Próxima Atracação
CLI -> CtrlOp: atracar_navio(session)
activate CtrlOp
CtrlOp -> MotorFila: obter_proximo_da_fila(session)
activate MotorFila
MotorFila -> MotorFila: calcular_score(navio)
note right: eh_perecivel == False\nSem bônus multiplicador
MotorFila --> CtrlOp: Retorna Navio com maior score da fila
deactivate MotorFila

CtrlOp -> DB: Busca primeira Vaga com status == StatusVaga.LIVRE
CtrlOp -> DB: Atualiza navio.status = StatusNavio.ATRACADO
CtrlOp -> DB: Atualiza vaga.status = StatusVaga.OCUPADA
CtrlOp -> DB: Cria instância de Atracacao (data_hora_inicio)
CtrlOp -> DB: session.commit()
CtrlOp --> CLI: Mensagem: Navio atracado com sucesso
deactivate CtrlOp
deactivate CLI
@enduml