@startuml
title Modelo de Domínio: Administração Portuária (Refatorado para a Realidade)
skinparam classAttributeIconSize 0

class Navio {
  - imo_id: String
  - nome: String
  - nome_capitao: String
  - companhia: String
  - status: StatusNavio
  - data_solicitacao: DateTime
}

class Carga {
  - id: Integer
  - descricao: String
  - categoria: String
  - quantidade_toneladas: Integer
  - eh_perecivel: Boolean
  - documento_alfandega: Boolean
}

class Vaga {
  - id: Integer
  - tipo_vaga: String
  - status: StatusVaga
}

class Atracacao {
  - id: Integer
  - data_hora_inicio: DateTime
  - data_hora_fim: DateTime
}

class ControladorCadastros <<Service>> {
  + solicitar_pre_cadastro()
  + auditar_solicitacoes_pendentes()
  + excluir_registro_navio()
  - _solicitar_classificacao_carga()
  - _auditar_documentacao_navio()
}

class MotorDeFila <<Service>> {
  + calcular_score(navio: Navio)
  + obter_proximo_da_fila(): Navio
  + exibir_fila_atracacao()
  + criar_subquery_score_cargas()
  + obter_expressao_score_total()
}

class ControladorOperacao <<Service>> {
  + atracar_navio()
  + registrar_desatracacao()
  + exibir_painel_vagas()
  + exibir_log_operacoes()
}

' Relacionamentos do Banco de Dados
Navio "1" *-- "1..*" Carga : transporta >
Navio "0..*" -- "1" Vaga : ocupa >
(Navio, Vaga) .. Atracacao

' Dependências das Camadas de Serviço
ControladorCadastros ..> Navio : gerencia >
MotorDeFila ..> Navio : prioriza >
ControladorOperacao ..> Atracacao : registra >

@enduml
