@startuml
title Diagrama de Estados: Ciclo de Vida do Navio

skinparam state {
    RoundCorner 20
    BackgroundColor White
}
[*] --> Em_Análise : solicitarPreCadastro()

state Em_Análise
state Validado
state Rejeitado

Em_Análise --> Validado : solicitarPreCadastro(status=VALIDADO)
Em_Análise --> Rejeitado : solicitarPreCadastro(status=REJEITADO)
Rejeitado --> Em_Análise : solicitarPreCadastro()

state "Em Fila" as EmFila
state Atracado
state Finalizado

Validado --> EmFila : calcularPrioridade()
EmFila --> Atracado : chamarProximoNavio()
Atracado --> Finalizado : finalizarAtracacao()

Finalizado --> [*]

@enduml