@startuml
title Diagrama de Estados: Estados do Navio

skinparam state {
    RoundCorner 20
    BackgroundColor White
    }

state Navio
state "Pré-cadastrado" as PreCadastrado
state "Aguardando documentação" as AguardandoDoc
state "Cadastro concluído" as CadastroConcluido
state "Navio liberado" as NavioLiberado

[*] --> Navio

Navio --> PreCadastrado : SolicitarCadastro()

PreCadastrado --> AguardandoDoc : SolicitarDocumentação()

AguardandoDoc --> Aprovado :  SolicitarDocumentação('aprovada')
AguardandoDoc --> Reprovado : SolicitarDocumentação('reprovada')

Reprovado --> [*]

Aprovado --> CadastroConcluido

CadastroConcluido --> Cadastrado : EnviarCadastro()

Cadastrado --> Fila : CalcularPrioridade()

Fila --> Atracado : chamarNavio()

Atracado --> NavioLiberado : finalizarAtracacao()

NavioLiberado --> [*]

@enduml
