@startuml
title Diagrama de Estados: Estados do Navio

skinparam state {
    RoundCorner 20
    BackgroundColor White
}

[*] --> Pendente : solicitar_pre_cadastro()

state Pendente
state Validado
state Rejeitado

Pendente --> Validado : _auditar_documentacao_navio(documento_alfandega=True)
Pendente --> Rejeitado : _auditar_documentacao_navio(documento_alfandega=False)
Rejeitado --> Pendente : solicitar_pre_cadastro()

Navio --> PreCadastrado : SolicitarCadastro()

Validado --> EmFila : calcular_score()
EmFila --> Atracado : atracar_navio()
Atracado --> Finalizado : registrar_desatracacao()

AguardandoDoc --> Aprovado :  SolicitarDocumentação('aprovada')
AguardandoDoc --> Reprovado : SolicitarDocumentação('reprovada')

Reprovado --> [*]

Aprovado --> CadastroConcluido

CadastroConcluido --> Cadastrado : EnviarCadastro()

Cadastrado --> Fila : CalcularPrioridade()

Fila --> Atracado : chamarNavio()

Atracado --> NavioLiberado : finalizarAtracacao()

NavioLiberado --> [*]

@enduml
