@startuml
title Diagrama de Estados: Ciclo de Vida do Navio

skinparam state {
    RoundCorner 20
    BackgroundColor White
}
[*] --> Pendente : solicitarPreCadastro()

state Pendente
state Validado
state Rejeitado

Pendente --> Validado : validarDescarga(status=VALIDADO)
Pendente --> Rejeitado : validarDescarga(status=REJEITADO)
Rejeitado --> Pendente : solicitarPreCadastro()

state "Em Fila" as EmFila
state Atracado
state Finalizado

Validado --> EmFila : calcularPrioridade()
EmFila --> Atracado : chamarProximoNavio()
Atracado --> Finalizado : finalizarAtracacao()

Finalizado --> [*]

@enduml