@startuml
title Diagrama de Atividades: Registro e Classificação de Prioridade

start
:Receber dados do Navio e Manifesto de Carga;
:Administrador audita a solicitação;

if (Dados são válidos? (RN03)) then (Não)
  :Notificar Tripulação;
  :Alterar status para Rejeitado;
  stop
else (Sim)
  :Alterar status para Validado;
  :Verificar natureza da carga (ehPerecivel);
  
  if (A carga é perecível?) then (Sim)
    :Aplicar Prioridade Máxima (RN04);
    :Reposicionar navio no topo da fila (pos[0]);
  else (Não)
    :Aplicar Prioridade Baixa;
    :Inserir navio no final da fila (FIFO);
  endif
  
  :Atualizar Dashboard de Gestão de Atracação;
  
  if (Existe Vaga Disponível?) then (Sim)
    :Autorizar Atracação Imediata;
  else (Não)
    :Aguardar na Fila de Atracação;
  endif
endif

stop
@enduml