@startuml
title Diagrama Entidade-Relacionamento (DER) - Porto do Itaqui
hide circle
skinparam linetype ortho

entity "navio" as navio {
  * imo_id : VARCHAR(20) <<PK>>
  --
  * nome : VARCHAR(100)
  * comandante : VARCHAR(100)
}

entity "carga" as carga {
  * id_carga : SERIAL <<PK>>
  --
  * imo_id : VARCHAR(20) <<FK>>
  * descricao : VARCHAR(255)
  * peso_toneladas : DECIMAL(10,2)
  * eh_perecivel : BOOLEAN
  * status_alfandega : VARCHAR(50)
}

entity "vaga" as vaga {
  * id_vaga : SERIAL <<PK>>
  --
  * tipo_vaga : VARCHAR(50)
  * status_disponibilidade : VARCHAR(20)
}

entity "atracacao" as atracacao {
  * id_atracacao : SERIAL <<PK>>
  --
  * imo_id : VARCHAR(20) <<FK>>
  * id_vaga : INT <<FK>>
  * data_hora_inicio : TIMESTAMP
    data_hora_fim : TIMESTAMP
}

entity "fila_espera" as fila {
  * id_registro : SERIAL <<PK>>
  --
  * imo_id : VARCHAR(20) <<FK>>
  * data_hora_entrada : TIMESTAMP
  * prioridade : INT
  * status : VARCHAR(20)
}

navio ||..o{ carga : "1:N"
navio ||..o{ atracacao : "1:N"
vaga ||..o{ atracacao : "1:N"
navio ||..o| fila : "1:1"
@enduml