@startuml
title Diagrama de Atividades: Gestão de Fluxo Portuário (v2)

|Capitão do Navio|
start
:Solicitar Pré-Cadastro (Navio/Carga);
note right: Inclui manifesto e\ndocumentos aduaneiros

|Administrador do Porto|
:Auditar Solicitação e Documentos;

if (Dados Válidos e Liberados?) then (Não)
  :Alterar Status para REJEITADO;
  stop
else (Sim)
  :Alterar Status para VALIDADO;
  
  if (Carga é Perecível? (RN01)) then (Sim)
    :Aplicar Prioridade MÁXIMA;
    :Reposicionar no Topo da Fila (pos[0]);
  else (Não)
    :Aplicar Prioridade BAIXA;
    :Inserir no Final da Fila (FIFO);
  endif
endif

:Gerenciar Fila de Espera;

while (Vaga Disponível? (RN02)) is (Não)
  :Aguardar em Fila;
endwhile (Sim)

:Registrar Início da Atracação (Timestamp);
:Registrar Saída/Desatracação;

stop
@enduml
