name: Deploy Documentação (MkDocs)

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar dependências do MkDocs
        run: pip install mkdocs-material mkdocstrings[python] mkdocs-glightbox
        
      - name: Construir site e publicar no GitHub Pages
        run: mkdocs gh-deploy --force